[2024-11-24T05:32:38.648+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T05:32:38.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: json_to_postgres.process_and_load_json manual__2024-11-24T05:32:36.552200+00:00 [queued]>
[2024-11-24T05:32:38.671+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: json_to_postgres.process_and_load_json manual__2024-11-24T05:32:36.552200+00:00 [queued]>
[2024-11-24T05:32:38.671+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-24T05:32:38.687+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_and_load_json> on 2024-11-24 05:32:36.552200+00:00
[2024-11-24T05:32:38.693+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-24T05:32:38.695+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2024-11-24T05:32:38.695+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'json_to_postgres', 'process_and_load_json', 'manual__2024-11-24T05:32:36.552200+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/json_to_postgresql.py', '--cfg-path', '/tmp/tmpuarq8smr']
[2024-11-24T05:32:38.697+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask process_and_load_json
[2024-11-24T05:32:38.960+0000] {task_command.py:467} INFO - Running <TaskInstance: json_to_postgres.process_and_load_json manual__2024-11-24T05:32:36.552200+00:00 [running]> on host ebfa98b31f20
[2024-11-24T05:32:39.035+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='json_to_postgres' AIRFLOW_CTX_TASK_ID='process_and_load_json' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T05:32:36.552200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T05:32:36.552200+00:00'
[2024-11-24T05:32:39.036+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-24T05:32:39.037+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-24T05:32:39.038+0000] {logging_mixin.py:190} INFO - Current task name:process_and_load_json state:running start_date:2024-11-24 05:32:38.663644+00:00
[2024-11-24T05:32:39.038+0000] {logging_mixin.py:190} INFO - Dag name:json_to_postgres and current dag run status:running
[2024-11-24T05:32:39.039+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T05:32:39.043+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/json_to_postgresql.py", line 19, in process_and_load_json
    port=DB_CONFIG["port"],
         ~~~~~~~~~^^^^^^^^
KeyError: 'port'
[2024-11-24T05:32:39.054+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-24T05:32:39.054+0000] {logging_mixin.py:190} INFO - Task start:2024-11-24 05:32:38.663644+00:00 end:2024-11-24 05:32:39.054002+00:00 duration:0.390358
[2024-11-24T05:32:39.055+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_and_load_json> dag:<DAG: json_to_postgres> dagrun:<DagRun json_to_postgres @ 2024-11-24 05:32:36.552200+00:00: manual__2024-11-24T05:32:36.552200+00:00, state:running, queued_at: 2024-11-24 05:32:36.574249+00:00. externally triggered: True>
[2024-11-24T05:32:39.056+0000] {logging_mixin.py:190} INFO - Failure caused by 'port'
[2024-11-24T05:32:39.056+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=json_to_postgres, task_id=process_and_load_json, run_id=manual__2024-11-24T05:32:36.552200+00:00, execution_date=20241124T053236, start_date=20241124T053238, end_date=20241124T053239
[2024-11-24T05:32:39.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T05:32:39.073+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 41 for task process_and_load_json ('port'; 82)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/json_to_postgresql.py", line 19, in process_and_load_json
    port=DB_CONFIG["port"],
         ~~~~~~~~~^^^^^^^^
KeyError: 'port'
[2024-11-24T05:32:39.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-24T05:32:39.270+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T05:32:39.276+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
